### ISSUE TITLE
x264 [error]: invalid width x height (0x0)

### ISSUE THREAD

**Issue by YogeshPhalak** [ISSuh/image2rtsp#1]
On making the specified changes in README.md and launching the launch file I am getting 'x264 [error]: invalid width x height (0x0)' , here is the detailed log 
``` bash 
roslaunch image2rtsp image2rtsp.launch 
... logging to /home/flytbase/.ros/log/47bcdca2-cb5f-11eb-927e-15698140e63b/roslaunch-flytbase-4090.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://flytbase:45645/

SUMMARY
========

PARAMETERS
 * /image2rtsp/encode_0: rgb8
 * /image2rtsp/fps_0: 10
 * /image2rtsp/port: 8524
 * /image2rtsp/proxyServerPort: 8564
 * /image2rtsp/sessionNumber: 2
 * /image2rtsp/srcHeight_0: 720
 * /image2rtsp/srcWidth_0: 1280
 * /image2rtsp/streamUrl_0: test0
 * /image2rtsp/subTopic_0: flytcam/image_raw
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    image2rtsp (image2rtsp/image2rtsp)

ROS_MASTER_URI=http://localhost:11311

process[image2rtsp-1]: started with pid [4106]
x264 [error]: invalid width x height (0x0)
[swscaler @ 0x5577b7ad2ce0] 0x0 -> 0x0 is invalid scaling dimension
[ERROR] [1623489572.274705914]: Cannot create SWS context
[ERROR] [1623489572.275462913]: Failed to [1] X264 Encoder Open
[image2rtsp-1] process has finished cleanly
log file: /home/flytbase/.ros/log/47bcdca2-cb5f-11eb-927e-15698140e63b/image2rtsp-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

**Comment by ISSuh** [comment]
> ```shell
> roslaunch image2rtsp image2rtsp.launch 
> ... logging to /home/flytbase/.ros/log/47bcdca2-cb5f-11eb-927e-15698140e63b/roslaunch-flytbase-4090.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://flytbase:45645/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /image2rtsp/encode_0: rgb8
>  * /image2rtsp/fps_0: 10
>  * /image2rtsp/port: 8524
>  * /image2rtsp/proxyServerPort: 8564
>  * /image2rtsp/sessionNumber: 2
>  * /image2rtsp/srcHeight_0: 720
>  * /image2rtsp/srcWidth_0: 1280
>  * /image2rtsp/streamUrl_0: test0
>  * /image2rtsp/subTopic_0: flytcam/image_raw
>  * /rosdistro: melodic
>  * /rosversion: 1.14.10
> 
> NODES
>   /
>     image2rtsp (image2rtsp/image2rtsp)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[image2rtsp-1]: started with pid [4106]
> x264 [error]: invalid width x height (0x0)
> [swscaler @ 0x5577b7ad2ce0] 0x0 -> 0x0 is invalid scaling dimension
> [ERROR] [1623489572.274705914]: Cannot create SWS context
> [ERROR] [1623489572.275462913]: Failed to [1] X264 Encoder Open
> [image2rtsp-1] process has finished cleanly
> log file: /home/flytbase/.ros/log/47bcdca2-cb5f-11eb-927e-15698140e63b/image2rtsp-1*.log
> all processes on machine have died, roslaunch will exit
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done
> ```

Under your log, it seems like you set two sessions. But ros image stream infomation is only one.
If you want only one session, try change to "1" about "sessionNumber" variable on launch file.

**Comment by ISSuh** [comment]
> On making the specified changes in README.md and launching the launch file I am getting 'x264 [error]: invalid width x height (0x0)' , here is the detailed log
> 
> ```shell
> roslaunch image2rtsp image2rtsp.launch 
> ... logging to /home/flytbase/.ros/log/47bcdca2-cb5f-11eb-927e-15698140e63b/roslaunch-flytbase-4090.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://flytbase:45645/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /image2rtsp/encode_0: rgb8
>  * /image2rtsp/fps_0: 10
>  * /image2rtsp/port: 8524
>  * /image2rtsp/proxyServerPort: 8564
>  * /image2rtsp/sessionNumber: 2
>  * /image2rtsp/srcHeight_0: 720
>  * /image2rtsp/srcWidth_0: 1280
>  * /image2rtsp/streamUrl_0: test0
>  * /image2rtsp/subTopic_0: flytcam/image_raw
>  * /rosdistro: melodic
>  * /rosversion: 1.14.10
> 
> NODES
>   /
>     image2rtsp (image2rtsp/image2rtsp)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[image2rtsp-1]: started with pid [4106]
> x264 [error]: invalid width x height (0x0)
> [swscaler @ 0x5577b7ad2ce0] 0x0 -> 0x0 is invalid scaling dimension
> [ERROR] [1623489572.274705914]: Cannot create SWS context
> [ERROR] [1623489572.275462913]: Failed to [1] X264 Encoder Open
> [image2rtsp-1] process has finished cleanly
> log file: /home/flytbase/.ros/log/47bcdca2-cb5f-11eb-927e-15698140e63b/image2rtsp-1*.log
> all processes on machine have died, roslaunch will exit
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done
> ```
